version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: openmarket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: openmarket
      POSTGRES_USER: openmarket_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: